<?php

/**
 * @file
 * Contains dmpa_subnationals_api.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_help().
 */
function dmpa_subnational_api_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the dmpa_subnationals_api module.
    case 'help.page.dmpa_subnational_api':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Restful endpoint for subnational data') . '</p>';
      return $output;

    default:
  }
}
/**
 * Implements hook_form_alter().
 */
function dmpa_subnational_api_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  if ($form_id == 'node_sdp_training_data_submission_form' || $form_id == 'node_sdp_training_data_submission_edit_form'){
    $form['#attached']['library'][] = 'dmpa_subnational_api/subnational_api';
  }
}